### ISSUE TITLE
Magnets for states in automata

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#112]

**Comment by Naereen** [comment]
I think it was added in #112, and it seems to work perfectly fine!
![Capture du 2021-02-03 13-07-36](https://user-images.githubusercontent.com/11994719/106744985-cbda4c80-6620-11eb-8090-c7b8f53e7a8b.png)

This can be safely closed?

**Comment by francoisschwarzentruber** [comment]
Yes, let us close that issue.
