### ISSUE TITLE
Unprivileged users can now write on protected shared boards

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#119]
Dear François,
It seems that anyone can write at anytime onto a shared board that does not grant any privileges.
A regressive bug?

**Comment by francoisschwarzentruber** [comment]
I think I forgot to update tableaunoir.irisa.fr :( 
PS: I cannot make the update automatic because for some unknown reason git pull asks me to write something in a text editor.

**Comment by philardine** [comment]
Thank you François, it was not during a course but when trying with a colleague... I'm going to test it now with my students!

**Comment by philardine** [comment]
It's OK :-)
