### ISSUE TITLE
Doesn't work with stylus

### ISSUE THREAD

**Issue by yannicklebras** [tableaunoir/tableaunoir#12]
Hi,
I tried the demo with my laptop Lenovo CHromebook. It has a wacom stylus working with the touch screen.
Tableaunoir does not work with this configuration : it draws only a little line of ~0.5cm.

On the screenshot bellow, the big lines have been made with touchpad, little ones with stylus.
![image](https://user-images.githubusercontent.com/48787735/97833051-a9a8f980-1cd4-11eb-9ebe-43c7470b3dfc.png)

Yannick LB

**Comment by francoisschwarzentruber** [comment]
Thank you for your message. I tried something. I think it is not perfect yet.
Note that there is no zoom, for simplicity.

There are still issues I think.
On iPad it seems worse, but I have no idea why.

**Comment by francoisschwarzentruber** [comment]
Hello, does it work better now?

**Comment by yannicklebras** [comment]
Hello,
It's not working on tableaunoir.github.io. Still have the same problem.
One problem more, the all right part of the tableaunoir seems to be inactive.

I tried on my smartphone : I can write with my finger.
But on my laptop with touchscreen, I can't (neither finger nor stylus).

Sorry for the delay.

**Comment by Vinetos** [comment]
Hello,

Nor with external Graphic Drawing Tablet

**Comment by francoisschwarzentruber** [comment]
Dear yannicklebras, dear Vinetos,

thank you for your message. By "Graphic Drawing Tablet", do you mean a Wacom graphic tablet that you plug by USB and that replaces a mouse?
On my computer, it works on Linux Fedora with both Firefox and Chrome and a Wacom Bamboo Tablet.

Could you give some details of your configuration?

Thank you in advance for your help.

**Comment by Vinetos** [comment]
I do not have any problems with Firefox.
Seems to be a behaviour on Brave browser / Chromium
I can reproduce the bug on
```
Brave: v1.16.76 (64-bit)
Chromium: 86.0.4240.198 (Official Build) (64-bit)
```

**Comment by yannicklebras** [comment]
Hi,

I tried with a wacom intuos on ubuntu and chromium browser : it works great.
My touchscreen is on a lenovo chromebook with recent update.

**Comment by francoisschwarzentruber** [comment]
On my Android Tablet, it works fine on Firefox and Chrome. It does not work properly with the Samsung Internet Browser.
PS: I added a way to modify the line width in the option menu.

**Comment by zak71** [comment]
Same issue with the little line then nothing using one by Wacom (their budget stylus and usb tablet) on Win 10. Shame as I really liked to look of it on my phone :-/

**Comment by m4lvin** [comment]
Maybe this helps, just for the record: It works fine with Firefox and Chromium on a thinkpad X1 tablet, which has a wacom digitizer as part of its touchscreen. However, under Firefox it is sometimes slow to start drawing, so for example `|_` becomes `\`. Under Chromium this does not happen.

**Comment by francoisschwarzentruber** [comment]
I do not know yet how to solve this issue. Do not hesitate to give more information, it will help a lot.

**Comment by yannicklebras** [comment]
I solved MY issue by adding 
`canvas {
    touch-action:none;
}
`
in the style css file.
Nowitworks great with my stylus on lenovo chromebook.

**Comment by francoisschwarzentruber** [comment]
Thank you @yannicklebras 
I added it in the css file! Hope it works better for people!
