### ISSUE TITLE
Export to PDF

### ISSUE THREAD

**Issue by rzach** [tableaunoir/tableaunoir#121]
The current export function makes one big .PNG file. This is hard to view if you have worked on more than one board.  It's also hard to print. This would be easier if there was a way to export to PDF with options: one long page, one PDF page per board, one PDF page per panel.

**Comment by francoisschwarzentruber** [comment]
I perfectly agree with you.
By the way, do you like the current horizontal scrolling of Tableaunoir?

**Comment by rzach** [comment]
I do. Maybe scrolling in any direction (or at least down) also?

**Comment by francoisschwarzentruber** [comment]
Dear Richard,
Thank you, because you gave me the motivation to start to implement a PDF export. The function seems working but it is not perfect yet (especially, the end of the board is a mess).
PS: I think I will keep the horizontal scrolling for now (and keep in mind for the vertical direction at some point... but not sure)

**Comment by brabalan** [comment]
When the number of half boards is odd, the last board seems to be missing.

**Comment by francoisschwarzentruber** [comment]
Dear brabalan,
oops, I can *not* reproduce the bug. On my computer I have:
- either the pdf ends with a full black page (meaning that the two last panels are on the page before the last one) <== a bit strange but at least nothing is lost
- or it ends with the last panel + an empty panel on the last page

**Comment by brabalan** [comment]
Do you still have access to the talbleaunoir I sent you? Because the pdf you generated was missing the last half-page. I have the `.tableaunoir` file available if necessary.

**Comment by brabalan** [comment]
(Please let me know if I should open another issue for this.)

Export to pdf always create many pages, even for a very small board. Could it be possible to limit the number of pages to the ones actually used?

**Comment by francoisschwarzentruber** [comment]
Dear brabalan,

thank you for pinpointing that problem. I think it is ok to continue with that issue. Do not worry!
I agree with you. I am busy these days, but I keep in mind that issue, and let you know when it is implemented!

**Comment by francoisschwarzentruber** [comment]
Hello, does PDF export work properly for you?

**Comment by brabalan** [comment]
It works great here, thanks.

**Comment by francoisschwarzentruber** [comment]
Thank you! OK. I close that issue then. Do not hesitate to open new issues if you have troubles with PDF export.
