### ISSUE TITLE
Keyboard shortcuts open search box in Firefox

### ISSUE THREAD

**Issue by rzach** [tableaunoir/tableaunoir#122]
If I type a keyboard shortcut (letter, not Ctrl+ combo) in Firefox (on Linux), tableaunoir does what it is supposed to do, but Firefox also thinks I want to search for a string and opens the search bar at the bottom of the page. This may be what's needed:

https://stackoverflow.com/questions/32616142/how-to-i-stop-clients-using-firefoxs-search-box-showing-up-when-playing-my-html?noredirect=1&lq=1

**Comment by francoisschwarzentruber** [comment]
I guess you have a plugin that does that for you. Because, on my Firefox (linux too), I have to press Ctrl+F to open the keyboard shortcut. On my side, I will study this issue asap.

**Comment by rzach** [comment]
It's a setting, but it's useful most of the time. Settings > General > Browsing option "Search for text when you start typing". I don't remember selecting it so it was probably on by default at some point.

**Comment by francoisschwarzentruber** [comment]
Thank you for the explanation. I understand now. It especially means that many users may really have this annoying problem. I will take of that soon.

**Comment by francoisschwarzentruber** [comment]
I think I solved the issue. I hope there are no side-effects ;). Thank you again!
