### ISSUE TITLE
Draw an official logo/icon ?

### ISSUE THREAD

**Issue by Naereen** [tableaunoir/tableaunoir#136]
I just noticed that tableaunoir does not have an official logo, and the websites doesn't have [favicon](https://fr.wikipedia.org/wiki/Favicon).

Maybe we could draw an official logo?

Using Tableaunoir itself would be fun, so here is my ~~ugly~~ proposal, drawn in 8 seconds (we can do much better, of course):
![Tableaunoir_logo](https://user-images.githubusercontent.com/11994719/108153654-de05c180-70db-11eb-9494-8a87e7e2dc3a.png)

I can provided the .tableaunoir file, but GitHub upload doesn't let me so there it is (zipped)
[tableaunoir_logo.zip](https://github.com/tableaunoir/tableaunoir/files/5993086/tableaunoir_logo.zip)

What do you think?
It could be added on the homepage of the project, near the top.

And we could draw a very simple favicon (using Inkscape and convert to .ico file) to the webpages?
Regards, @Naereen

**Comment by francoisschwarzentruber** [comment]
Dear Naereen,
thank you for your proposal which is cute. I think it is a nice idea. Other ideas could be:
- an icon which a big black square
- or an icon which a big black square with a T written on it (T recalls the \top symbol for truth in logic)

What do you think?

**Comment by kannaig** [comment]
It's a very good idea Naereen! 
May I propose an icon too?
![craie](https://user-images.githubusercontent.com/65854396/108182698-972ec080-7109-11eb-91c5-785af69d1530.png)

**Comment by kannaig** [comment]
![craie_version_fond_vert](https://user-images.githubusercontent.com/65854396/108185208-56847680-710c-11eb-8f3a-00def9a5ab68.png)
or a green version

**Comment by Naereen** [comment]
> ![craie_version_fond_vert_bis](https://user-images.githubusercontent.com/65854396/108187826-2ee2dd80-710f-11eb-8f34-224f42ffb99e.png)
> 
> ![craie_version_fond_vert_bis_petit](https://user-images.githubusercontent.com/65854396/108188114-7e290e00-710f-11eb-9219-47c6fbd1637c.png)
> 
> ![image](https://user-images.githubusercontent.com/65854396/108190611-774fca80-7112-11eb-89f5-4afbd9e63e10.png)
> 
> or a green version

Way better than mine :+1:!

**Comment by kannaig** [comment]
Thanks Naereen.

**Comment by francoisschwarzentruber** [comment]
Thank you Naereen for this idea. Thank you kannaig for the logo! :)

**Comment by Naereen** [comment]
Great I see it was added as a favicon, it looks very nice, good job @kannaig !
