### ISSUE TITLE
PDFs are inserted below background layer.

### ISSUE THREAD

**Issue by tekhnee** [tableaunoir/tableaunoir#140]
Dear @francoisschwarzentruber,

I would swear that a similar bug report was submitted weeks ago — and then promptly fixed. Unfortunately I can't find it in the list of closed issues.

Anyway, PDFs are currently inserted below the backgrounds (staff paper, grid, etc.). Is this by design or a bug? My understanding is that the order of layers, from topmost to bottommost, should be the following:

— Magnets
— Drawings
— Embeds (PDF, images)
— Background patterns (grids, staves, etc.)

Thank you!

**Comment by tekhnee** [comment]
Update: Curiously, image files (.png) dragged-and-dropped into tableaunoir are rendered *above* the drawing layer on my instance.

**Comment by francoisschwarzentruber** [comment]
Dear @tekhnee ,

Sorry for that. I agree with you. A bug was "inserted" when I reorganized the code and simplified the implementation. Now it should work normally again.
Concerning, your second comment: yes, drag-and-drop images because magnets.

PS: I remember we discussed that at some point and that you had a nice idea of moving the background objects too. I am still thinking of that. Something like, a menu where embeds could be transformed into magnets for positionning and then magnets could be pushed back as embeds.

**Comment by tekhnee** [comment]
Good morning, @francoisschwarzentruber, and thank you for the quick fix.

I confess our discussion had escaped me when I reported the bug. Now I remember, and it makes sense!

((For future reference: Might the distinction between "magnets" and "embeds" be too implementation-oriented to play into the UI? I understand you perfectly, but one might argue that users simply think in terms of "layers" whereby objects can be "sent forward" or "pushed backward."))

**Comment by tekhnee** [comment]
@francoisschwarzentruber, very sorry to be a nuisance on a fair weekend — I just can't get the PDF layer fix to work. It still appears below the background. I'm confident it is not a browser caching issue. Would you confirm that this works as expected on your end? Many thanks.

**Comment by francoisschwarzentruber** [comment]
Do not worry. It is always a pleasure to have news from you and to read you. Here is what I get:

![image](https://user-images.githubusercontent.com/43071857/108595257-27c20680-737f-11eb-9e98-694bac76cf9e.png)

The order is:
- first background color (in the example: black)
- then wallpaper (in the example: music score staffs)
- the image and PDF layer (in the example: the pdf with some maths) 
- then the board itself (in the example "Hello")
- finally magnets (here magnet on which it is written "magnet")

Is that correct?
At your place, it is not shown in that order, isn't it?

**Comment by tekhnee** [comment]
@francoisschwarzentruber I'm embarrassed to say that your latest commit hadn't been pulled into my local mirror. It took me two hours of aimless "debugging" to realize… (end-of-week exhaustion?) My sincere apologies for the false alarm. Confirming this works well.

**Comment by francoisschwarzentruber** [comment]
Dear tekhnee, thank you! Do not feel embarrassed at all.
(sorry for the late answer)
