### ISSUE TITLE
Websocket closed (?) during shared session.

### ISSUE THREAD

**Issue by tekhnee** [tableaunoir/tableaunoir#141]
Dear @francoisschwarzentruber 

I tested my self-hosted instance yesterday with 5 other participants in three continents. The share link was generated by myself and sent to the other participants via Zoom.

Unfortunately, sharing stopped working within minutes. None of the 5 participants received updates on my drawings, neither would their cursor movements be visible on my station.

In the end we completed the session without a whiteboard, using Zoom screen sharing.

Hours later, I returned to the computer, and noticed that the number of (ostensibly) connected participants, according to the indicator on the toolbar, was still the same (5) as if no one had disconnected. Finding this number suspicious, I refreshed the browser and indeed, as it turned out, I was the only one left in the session.

I suppose this suggests a websocket that was closed during the session. Is that correct? What could be the underlying cause?

My internet connection was perfectly stable — Zoom worked all along.

Many thanks!

**Comment by francoisschwarzentruber** [comment]
Dear @tekhnee,

thank you for your message. I think the shared board functionnality is not completely mature and must be improved. I guess that the internet connection was not perfect, but Zoom provides mechanisms to repair the connectivity issues.

I am not an expert in networks, but I will try to do my best. I think it would be nice if an expert in networks could help us for that issue.

**Comment by francoisschwarzentruber** [comment]
I implemented a (not completely tested) heartbeat mechanism. Each user emits a heartbeat -- let say every 2sec. If the server does not hear any messages from a user during 10sec, it detects that the connection is broken and broadcast to the other users that that particular user is out.
PS: #141 is not deployed yet on irisa.fr.

**Comment by francoisschwarzentruber** [comment]
Here are some ideas for improving the reliability:
- still improve the heartbeat protocol
- maybe use a ping/pong protocol instead
- compute the quality of the network
- automatic reconnection in case of failure (could be transparent to the user)
- use WebRT that is, clients are connected together directly and messages do not go through the server anymore. The server is only here for the clients to meet.

I guess some of these ideas and even more involved ideas are used in Zoom and other professional pieces of software. As the topic is difficult, maybe another option would be to use a library that handles all of that.

Questions:
- What are the best solutions?
- Do you know some library that handle reliability of Websockets transparently?

**Comment by tekhnee** [comment]
It's a controversial subject. [Socket.io](https://socket.io/docs/v3/index.html) is considered a kitchen-and-sink solution, very easy to use, but also somewhat bloated. It is supposed to support automatic reconnections in case of dropouts. Amusingly, one of the demo apps is a simple [whiteboard](https://socket.io/demos/whiteboard/).  You may also find a comparison between WS and Socket.io [here](https://www.hackdoor.io/articles/differences-between-websockets-and-socketio-30de2e05584e).

**Comment by francoisschwarzentruber** [comment]
I think it is now less a problem.
1. data are also saved locally in case of disconnection
2. So if you press F5 you will see your own data, except if another user sends you data
Now, the best of the best would be to implement a reconnection procedure. (if a client disconnects, it tries to reconnect automatically without pressing F5)

**Comment by francoisschwarzentruber** [comment]
Thank you @tekhnee. We will soon improve the reconnection procedure (hopefully). I think Websocket are unreliable by nature.
