### ISSUE TITLE
Spanish version not working

### ISSUE THREAD

**Issue by JulioLoayzaM** [tableaunoir/tableaunoir#151]
Hi @francoisschwarzentruber,

I've noticed the Spanish version is not working. I think I found the issue and will submit a PR for it, though I would also like to incorporate @Kerl13 's reviews from #128 to improve the translation, if that's fine.

Thanks!

**Comment by francoisschwarzentruber** [comment]
Hi Julio,
Thank you for posting that issue and for improving the Spanish version.

**Comment by francoisschwarzentruber** [comment]
Hello Julio,
does the Spanish version work? If yes, shall we close that issue?

**Comment by JulioLoayzaM** [comment]
Hello François,
Yes, the Spanish version works now. There are some parts here and there that aren't translated but that seems to be the case with all translations. We can open a new issue regarding those parts, but we can close this one. Thanks!
