### ISSUE TITLE
Can no longer divide screen

### ISSUE THREAD

**Issue by agnelmeme** [tableaunoir/tableaunoir#157]
Using keystroke 'd' or clicking on divide screen in the toolbar no longer draws the split line. (the animation still works but not the action)

**Comment by francoisschwarzentruber** [comment]
Thank you for reporting this bug. The bug came from the improvement of the background color module. It was located in the computation of the color used for dividing the screen, that depends on the background color.

**Comment by agnelmeme** [comment]
Thanks for the prompt reply and thanks for this great app!
