### ISSUE TITLE
Filling a shape with/wihtout pattern

### ISSUE THREAD

**Issue by osankur** [tableaunoir/tableaunoir#192]
When one hits f after drawing a shape (say, a circle), it fills the shape with some "impressionist" pattern. However, the natural behavior I would expect is that it fills the shape without any pattern.

**Comment by francoisschwarzentruber** [comment]
Thank you for have post this issue. Now, the filling depends whether you use Tableaunoir in the normal mode or the artistic mode.
Normal mode: the filling is uniform (slightly transparent so that you can write on the top of it.
Artistic mode: the filling with some  "impressionist" pattern
