### ISSUE TITLE
Saving and loading with magnets

### ISSUE THREAD

**Issue by osankur** [tableaunoir/tableaunoir#194]
When one creates a figure with magnets, say, an automaton whose states are magnets, saves this in a tableaunoir file, and loads it on another window, the magnets initially appear misplaced. Nevertheless, when one moves one magnet, all magnets seem to regain their positions immediately.

When loading such a file, some magnets with latex equations do not get evaluated (they remain plain text), while some other latex magnets remain invisible. Those that are invisible regain visibility when one creates a fresh magnet with latex equation.

**Comment by francoisschwarzentruber** [comment]
Sorry for the delay. Do you still experience that problem?

**Comment by osankur** [comment]
I cannot reproduce the problem in the current version at this moment.

**Comment by francoisschwarzentruber** [comment]
Thank you. I will close the issue, et and we may reopen it if there are some troubles with loading/saving the magnets.
