### ISSUE TITLE
Save and load create shadows of magnets

### ISSUE THREAD

**Issue by Ragdub** [tableaunoir/tableaunoir#212]
When saving and loading a file, sometimes a drawing that was first deleted appears. It disappear as soon as I use CTRL+Z (even not on the drawing).

I am able to replicate this at will: the operations are:
1) draw something (ex an arrow)
2) create a magnet from the arrow
3) paste the magnet (and then move it)
4) erase the copy (with the rubber for instance, works also with CTRL+X) 
5) save and load

**Comment by francoisschwarzentruber** [comment]
Thank you @Ragdub , especially for the detailed recipe to reproduce the bug. Indeed, I was able to reproduce the bug! I will try to fix it!
