### ISSUE TITLE
Moving the board is not working on iPad

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#232]
It seems to be related to Webkit.

**Comment by pcharbit** [comment]
Not sure it is related to WebKit, the problem occurs on safari, Firefox and chrome on iPad

**Comment by francoisschwarzentruber** [comment]
Maybe not. I do not know.
At least there is a bug in Webkit concerning the scroll and I am experiencing it on Gnome Web: https://bugs.webkit.org/show_bug.cgi?id=238497

And also, it appears that Firefox is maybe using Webkit on iOS: https://www.numerama.com/tech/33191-firefox-ios-webkit.html

**Comment by Pierre-erreiP** [comment]
Oh yeah you are right in fact Apple forces everyone to use webkit, so that is also true for chrome
https://www.igen.fr/ios/2022/03/des-developpeurs-veulent-supprimer-le-monopole-de-webkit-entretenu-par-apple-sur-ios-128495
https://open-web-advocacy.org

**Comment by francoisschwarzentruber** [comment]
Hello @pcharbit, and hello @Pierre-erreiP !
thank @Pierre-erreiP for the information about Webkit and Apple!

Well, I have partially solved the issue. On Webkit that has the bug with smooth scrolling, you will just have a brutal scrolling! At least I think it works. On Gnome Web (which is a Gnome browser application relying on Webkit), it is working now.

@pcharbit: is it ok for you now?

**Comment by Pierre-erreiP** [comment]
yes this works now thanks! (@pcharbit and @Pierre-erreiP are the same person...)

**Comment by francoisschwarzentruber** [comment]
Happy that it works for both of you @pcharbit and @Pierre-erreiP even if you are the same person ;).
ps: Sorry: you do not have the animation of the board that is scrolling. ;)
