### ISSUE TITLE
Broken Export

### ISSUE THREAD

**Issue by JoanThibault** [tableaunoir/tableaunoir#235]
Hi,

I've encountered a strange issue, the only "strange" thing I did on this case was to change from "black" background to "white" background and finally "black" again

[myblackboard.zip](https://github.com/tableaunoir/tableaunoir/files/9757710/myblackboard.zip)

![myblackboard (6)](https://user-images.githubusercontent.com/22982262/195139098-34ebf092-e7bb-4e9a-ba94-c6a732ea32c1.png)

[download (3).pdf](https://github.com/tableaunoir/tableaunoir/files/9757700/download.3.pdf)

The issue is that only the first page is displayed in either the image or pdf export

**Comment by JoanThibault** [comment]
Glad to help.
Thank you for maintaining and developing this very useful tool :-)

**Comment by francoisschwarzentruber** [comment]
Do not hesitate to reopen that issue if needed!
