### ISSUE TITLE
Swapping between palettes breaks default palette if a higher number color is picked

### ISSUE THREAD

**Issue by Bluebottel** [tableaunoir/tableaunoir#242]
How to reproduce:

1. In the options Switch to the 21 color palette
2. Go back to the blackboard.
3. Pick a color with an colorID above 7
4. In the options switch back to the default color palette
5. Go back to the blackboard
6. Click the color picker button

Expected behavior is for the color picker circle menu to show but it causes this error instead

`Uncaught TypeError: this.buttons[this.currentColorID] is undefined`

**Comment by francoisschwarzentruber** [comment]
Thank you for having spotted that issue, and also having solved it!
