### ISSUE TITLE
Edit LaTeX magnet text

### ISSUE THREAD

**Issue by jmgorius** [tableaunoir/tableaunoir#28]
When creating a magnet with a LaTeX formula, trying to edit the text again proves rather difficult: one can erase parts of the formatting, characters, etc. but not edit the formula. It would be nice if the original LaTeX text was displayed when trying to edit the magnet contents.

**Comment by francoisschwarzentruber** [comment]
The easier thing would be to disallow for LaTEX equations inside some other normal text. So a text magnet could be of at least two types? normal (text) and formulas (LaTEX). See issue #81.

**Comment by jmgorius** [comment]
The interpreted text magnets mentioned in issue #81 seem to be a good compromise.

**Comment by francoisschwarzentruber** [comment]
LaTEX magnets can be modified by double-clicking on it!

**Comment by jmgorius** [comment]
Very nice! Thanks a lot!

**Comment by francoisschwarzentruber** [comment]
I am happy it works. Well, the "LaTEX editor" could be better (now it just a standard JS prompt). But I guess users only type simple LaTEX formulae, so I guess it is enough.
Merry christmas!
