### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by Farenheid** [tableaunoir/tableaunoir#30]
Hi,
I'm busy translating tableaunoir in French. I am presently doing it in the code itself, but it would be better to use some locale library or included file to do it. Do you plan to use a particular library in a future release ?
May I push my translated file somewhere ?
Thanks.

**Comment by francoisschwarzentruber** [comment]
Hi,

thank you for your enthousiasm! That's a very good idea to translate tableaunoir in french! I think it would be better to wait a bit in order to do it in a proper way. The problem is that index.html may change over time and then the translation may become obsolete.

Do you know any idea to proceed? I suggest to have a file fr.json that contains 

{
           "<text in english>": "<translation in french>"
}

and maybe use a webservice to translate the part that are not in that fr.json file?

What do you think?

**Comment by Farenheid** [comment]
Using a json file would be reasonable. But calling a webservice to translate not-already-translated strings would involve one cannot run tableaunoir without internet connection. Moreover, a webservice translation could break global translation consistency since a human translator will use a glossary which, hopefully, will remain constant through the whole translation. A webservice does not know about it. As an example, the word "magnet" becomes "aimant" in French. In almost every context, that is right, but not for tableaunoir, for which I think "magnet" should remain "magnet". IMHO, untranslated strings should be left untranslated until the release of a new translation file.
Well, I bet there won't be thousands of new words or sentences added to each new version. Translating them will take a few minutes at most (it took me less than 20 minutes and a cup of coffee to translate tableaunoir in French). tableaunoir is becoming more and more popular among my fellow-teachers in our school, I will keep on with the job.
BTW, there is a trick. Not only index.html shoud by made translation-aware, but also js/User.js, in User class, switchChalk and switchErase methods.

**Comment by francoisschwarzentruber** [comment]
Hello,
thank you for your message. I agree that calling a webservice is maybe too much.

1) First, I removed the text in js/User.js. All the text is in the index.html.
2) Second I added a translation module.

You are welcome to modify **src/fr.json**. 
Then, you can access to the french version of tableaunoir at the following address:

https://tableaunoir.github.io/?lang=fr

What do you think?

Have a nice coffee!

**Comment by Farenheid** [comment]
Nicely done. Thanks.
fr.json is coming soon... BTW, button titles do not get translated.

**Comment by francoisschwarzentruber** [comment]
Thank you for taking care of the translation in french! Now it should work. (and if not, it should at some point, in the future).

**Comment by Farenheid** [comment]
My pleasure.
Sorry, I am no JS developper (better in C and bash scripts), I am actually trying to understand how to encode the many strings which include carriage returns and tabulations in json format. Most of them do not get translated, even if I write escaped characters as \n or \t. Problems with strings containing <em> tags also, they are not recognized by the parser.
I am surely doing something wrong... still investigating.

**Comment by francoisschwarzentruber** [comment]
For which text do you need returns and/or tabulations?

**Comment by Farenheid** [comment]
Almost every text line is spawned into several idented lines. Trying to just treat them as plain html does not work, I have to write every single tab or LF to have them recognized by the translation parser. AFAIK, the translateElement method in Translation.js is recursive and handle innerHTML contents. That may be a problem. For instance, have a look at the part "About tableaunoir". Every div (class explanation) element inner html is indeed an img tag followed by some text, containing em tags. To make the translateElement method take it into account, I would have to copy everything, including the img tag. Simply copying the text line does not work.
I wonder if it would be possible to simplify it by: replacing every text in index.html by "MessageXXXX", create a base en.json file containing every text line in the form "Message0001": "Menu", "Message0002": "Colors" and so on... It would make translating a lot easier (future translators for other languages will just have to follow messages in en.json, they won't have to read the entire index.html file to find every single text line they have to translate), and the translate system would just become simple strings substitution, without having to care about "what is where" (innerHTML, title properties and so on...). Of course, the default language would be en, if no language is specified in url.
I may have missed something. This is just plain-C-like thinking, I bet. Maybe there is something simpler that I don't know.
Thanks.

**Comment by francoisschwarzentruber** [comment]
OK I see the problem! I think the "MessageXXX" solution is nice but maybe over-complicated. I think the HTML code could be modified as follows: I added <span>...</span> around the text that needs to be translated (1).

What do you think?

**Comment by Farenheid** [comment]
Still hard to detect multilined text elements. Do you use some kind of auto-indent IDE ? This may be a problem in the future, since we cannot be sure word wrapping will always be done the same way, nor there will always be the same amount of tabs in the front of each line.
For instance: in the menu, "Keyboard shortcuts" has to be written as "Keyboard\n\t\t\t\tshortcuts" to be correctly detected and replaced by the translateElement method. I haven't managed yet to translate sentences like "Tableaunoir is an online blackboard. It is ideally used with...", I simply cannot determine how many \t or \n I should use and where (I have already tried a dozen combinasions).
My suggestion: use only one-lined text elements, or replace them by non-spaced delimited templates like "[About]", "[ClearTheBoard]", or "[ThisIsOpenSource]", and have your translate lib make simple strings substitutions. I agree it may look complicated, it will probably obfuscate the html code a few, but that kind of template will remain constant in time. Actually, I think to-be-translated messages should have some kind of unique ids.
Does it make sense ?
Thank you.

**Comment by francoisschwarzentruber** [comment]
It makes sense. I suggest the following, based on your idea: use IDs!

### How to proceed
If not existing yet, add **id="thisIsOpenSource"** to the specific div or span that needs a translation.

Then in **fr.json**, you can do:

{  
    "#thisIsOpenSource": "Ce logiciel est libre."
}

We use # because that is the traditional symbol for referring to an id in DOM selectors.


### Example
I updated Tableaunoir for that. See https://tableaunoir.github.io/?lang=fr with **fr.json** being:

{
	"Text": "Texte",
	"↩ Cancel": "↩ Annuler",
	"#buttonLeft": "Gauche"
}

**Comment by francoisschwarzentruber** [comment]
Dear Farenheid,

I hope you are fine. The HTML code is completely clean. Each text should be in a div. I suggest that you translate already what you can. Do not worry for the rest, we will discuss how to proceed.

Anyway, thank you and have a nice day.

**Comment by Farenheid** [comment]
Hi, I added ids to many tags in index.html, and now I am writing fr.json. I am new to github and don't know how to commit index.html...

**Comment by francoisschwarzentruber** [comment]
Hi,

I hope you are fine. You work on your own repository: you commit and push on your own repository. After that, you do a "pull request".
Note that the repository of tableaunoir has changed: it is https://github.com/tableaunoir/tableaunoir instead of https://github.com/tableaunoir/tableaunoir.github.io (which contains the deployed website).

Thank you for your contribution.

**Comment by francoisschwarzentruber** [comment]
Dear Farenheid,
I did not have news from you. I hope you are fine. The translation process is now better to use. fr.json is almost finished.
Merry christmas.

**Comment by Naereen** [comment]
Hi @Farenheid and @francoisschwarzentruber,

I think this translation issue can be closed, and new ones should be opened if users ask for a new language.

I updated the French #126 and German #127 translations, and added Spanish too #128. I'll translate the last parts of the documentation #129.
