### ISSUE TITLE
Consider having some smoothing?

### ISSUE THREAD

**Issue by Kerl13** [tableaunoir/tableaunoir#34]
This is no big deal but I find my text and drawings not very smooth (the "hello" part is good but you can see the broken lines on the other symbols):

![image](https://user-images.githubusercontent.com/11668385/98465264-59480500-21c8-11eb-8880-10ccfbe79d32.png)

It also happened to become worse after adding many half-boards.

I imagine it is not related to tableaunoir but rather to my slow laptop / slow firefox / the js engine not scheduling enough "mouse" events per second / another reason?
I observe the same behaviour on https://awwapp.com/ but they seem to fix this issue by smoothing the line right after I raise the pen. I think their smoothing is a bit too violent but I like the idea.

So:
- do you observe the same behaviour?
- do you know how hard it would be to add a little bit of smoothing in tableaunoir?

(Side note: the [xournal++](https://github.com/xournalpp/xournalpp) desktop app gives my smooth lines without post-processing, it suggests it is indeed browser/js related).

**Comment by francoisschwarzentruber** [comment]
I observe the same behavior on Firefox. Chrome gives better results.

PS:
Awwapp is based on svg, some they can easily handle that. Tableaunoir is based on canvas, like google jamboard. It is also possible but slightly more trickly.
Tableaunoir is based on canvas for... the creation of the magnets!

**Comment by francoisschwarzentruber** [comment]
I think it is related to the efficiency of the canvas element.
In Chrome, there is a bug. It is very efficient on a blackboard. Then, you switch to whiteboard, and suddently, drawing is very slow. The cause: there is a bug in Chrome that desactive the hardware acceleration for canvas when pixels are modified (https://www.reddit.com/r/javascript/comments/ac9hdb/calling_getimagedata_potentially_puts_you_canvas/).

**Comment by DamsNg63** [comment]
This seems to be happening only after I use the eraser for me.

**Comment by tekhnee** [comment]
@francoisschwarzentruber, grateful for the canvas-based foundations of Tableaunoir. I've yet to see an SVG-based implementation with decent erase support, for instance.

**Comment by francoisschwarzentruber** [comment]
Dear DamsNg63,
thank you for your comment. What is your browser? On my computer and Android Tablet, I do not have that issue: if I erase, it is still fast. Well, if really I am very fast with my mouse or pen, I can have this kind of behavior. But in real use, it never happens. (except by changing the background color in Chrome, but then, if I re-extend the canvas, it is fast again -- probably Chrome is switching the hardware acceleration on again for an obscure reason).

**Comment by DamsNg63** [comment]
> Dear DamsNg63,
> thank you for your comment. What is your browser? On my computer and Android Tablet, I do not have that issue: if I erase, it is still fast. Well, if really I am very fast with my mouse or pen, I can have this kind of behavior. But in real use, it never happens. (except by changing the background color in Chrome, but then, if I re-extend the canvas, it is fast again -- probably Chrome is switching the hardware acceleration on again for an obscure reason).

I am using Chrome with a drawing tablet. I tried multiple things, I can write during a very long period of time without having issues, and even if I refresh the page and start using the eraser without writing anything I will still have the issue.
On Safari the line width is awfully thin, so for now in order to erase content, I just use the black pen (which is time consuming...).

**Comment by Kerl13** [comment]
In relation to my initial question: things are indeed much smoother on chromium than firefox, thanks for pointing this out.

That being said, I observe the same behaviour as described by @DamsNg63 (this is a second issue actually), more details:

1. Initially when I draw, say on chromium, it's reasonably smooth (leftmost "hello" on the picture);
2. then if I use the eraser, then newly drawn lines are broken (middle "hello");
3. and if I cancel something (whatever this is) by hitting Ctrl-Z, drawing becomes smooth again (rightmost "hello").

![image](https://user-images.githubusercontent.com/11668385/101244383-85db3800-3706-11eb-938b-bc1df44bdcea.png)

**Comment by francoisschwarzentruber** [comment]
Dear tekhnee,

thank you for your message. Choosing between SVG or canvas was/is still a big question. But the philosophy of Tableaunoir relies on canvas. And indeed the main argument for canvas was the eraser.

Here are the main arguments for using canvas.
- During teaching, one has no time/energy to think about objects when writing/drawing. And if one needs objects, one can use "magnets".
- I think it is more frequent to need to erase exactly what is under the eraser, than erase the entire object.
- one wants to select a zone, duplicate etc. even if it would have been small portions of some SVG objects. Complicated to implement with SVG.
- SVG is nice for zooming: the rendering is always nice. But I think Zooming is confusing for students.
- Canvas allows for effects. Maybe in the future: partial transparent erasing, some chalk effects.

**Comment by francoisschwarzentruber** [comment]
Dear Kerl13, dear  DamsNg63,

@DamsNg63, thank you: I think you pinpointed a source of the fall of efficiency (using the eraser).
@Kerl13, thank you for the detailed procedure (step 1, 2, 3) that shows that the efficiency is changing, depending on some internal state of the canvas. I think that your procedure will help to figure out which features of the internal state are responsible for the fall of efficiency.

This issue has to be solved at some point.

**Comment by francoisschwarzentruber** [comment]
I cannot reproduce the efficiency drop on my devices. My drawing remains smooth even after erasing. I will continue thinking about that issue though.

**Comment by francoisschwarzentruber** [comment]
I will soon consider to add smoothing. But, smoothing should depend on the local speed so that:
- If one draws a rectangle, the corner should not be smoothifyed.
- No undesirable "corners" appear in a curve drawn quickly
