### ISSUE TITLE
Chat text does not disappear for shared screen

### ISSUE THREAD

**Issue by FrPellegrini** [tableaunoir/tableaunoir#35]
When sharing a screen between two people (and more ?), the sharer can click on the messages to make them disappear from the bottom of the screen. However, the sharee cannot do the same. The text takes more and more space on the bottom of the screen, and hides the pictures.

**Comment by francoisschwarzentruber** [comment]
Now, everybody can remove the messages on its own screen.This chat is still a bit in development. The idea is that you can comment like in a TV show.

**Comment by FrPellegrini** [comment]
But when the sharer removed them, they did not disappear on the sharee's screen. That's a bit of a problem.
Since it is in development, maybe set a toggle on the sharer's dashboard to enable or disable it ? Hence it won't be a problem if a teacher wants just to use the drawing tool and uses other media (e.g. Mattermost & co) to interact with the pupils on another channel ?

**Comment by francoisschwarzentruber** [comment]
Do you think that when the sharer click on a message, the message should disappear on *all* screens?

**Comment by francoisschwarzentruber** [comment]
Note that the notion of sharer is not properly defined yet. Any student can steal the rights of the sharer, but the sharer can steal it again... I think the sharer should have a special "sharer" url with more rights.

**Comment by FrPellegrini** [comment]
Yes, indeed. That would mean that the sharer has pedagogically acknowledged of the content of the message and consider it of no longer use.

**Comment by FrPellegrini** [comment]
Yes, indeed, the sharer mus have more rights. Else rogue students might hack the tool and make it useless as regards class discipline. That would prevent any use in middle- and high schools.
You have this in BBB (notion of "moderator") or Zoom (notion of "host"), for instance.

**Comment by FrPellegrini** [comment]
All the more users ate not identified by name on the system. Hence, a teacher would not be able to sanction a pupil that starts making some fuss. Since identification is not desirable sinci it would limit the ease of use, some other protection mechanism must be put in place so that the teacher is not unduly disturbed.

**Comment by francoisschwarzentruber** [comment]
OK. I see two possibilities:

**To provide *two* URLs (like framadate)**
a) the admin "sharer" link that provides all the rights
b) and the user "sharee" "student" link.

**To set a password or receive a small password from the server**
This password is used if the sharer (the teacher) looses the connection. When s.he reconnects, s.he can recover her.is rights by typing the password.

What do you prefer?

**Comment by FrPellegrini** [comment]
I agree with you about the special URL for the sharer. The sharee must not be able to get the sharer's URL by removing the URL extension. The sharee's URL must be really different.

**Comment by FrPellegrini** [comment]
Passwords would hinder the usability of your tool. It would require to have an e-mail account, read it, etc.
During a remote class (e.g. on Discord or such), the teacher would open another browser tab, start a "tableaunoir" instance, get the sharee's URL and copy-paste it (might be good to have a "add to clipboard" button close to it ! ;-) ) to the Discord, so that pupils can in turn open a tab on their browsers.

**Comment by francoisschwarzentruber** [comment]
Let us opt the two URLs solution then!

**Comment by FrPellegrini** [comment]
Afterthought : if the sharer shares her/his screen, then the pupils might see the sharer's URL.  :-(

**Comment by FrPellegrini** [comment]
It means that there should be some "secret" kept somewhere in addition...

**Comment by francoisschwarzentruber** [comment]
Hence, maybe the solution of a password. By password, I do not mean to have an account, an email... Just a code that you send (or that the server gives you, may a number like a credit card number).
That code enables you to recover the sharer rights in case you got disconnect!

**Comment by FrPellegrini** [comment]
Yes. You are right. So the "password" option might be the safest way to be sure that a sharer's instance cannot be stolen...
And it would allow another merit : be able to give rights to another teacher to take moderator rights on the same tableaunoir, e.g. to relay with someone else...

**Comment by francoisschwarzentruber** [comment]
Of course, a session will not be very secure. But it will prevent some fuss.

**Comment by FrPellegrini** [comment]
In the use case of someone sharing her/his screen, better security would be achieved if the password is typed in "blind mode" by the person, rather than being exposed somewhere on the dashboard. In the latter case, when the sharer goes to the dashboard, the password would be seen by the pupils, which would ruin the secret...

**Comment by FrPellegrini** [comment]
The advantage of your tool is simplicity of use. It is not meant to be "secure", but to allow teachers to be quite confident about the fact that pupils will not make fuss if they do not allof them to (e.g. remove chat or drawing rights).

**Comment by FrPellegrini** [comment]
Hence, the idea is that people who create a tableaunoir would be asked to enter a password to protect/unlock their instance, or proceed without sharer rights. Then, when the URL is shared, pupils would use it as no moderator, and another teacher would be able to click to enter the password, and get moderator rights if the password is correct. It would be up to the teachers to share this secret by way of another medium.

**Comment by francoisschwarzentruber** [comment]
To sum up the discussion.

**Protection**
A code typed by the sharer in blind mode, before clicking on sharing. If no code is typed, then the shared link is simply not protected.

**Rights**
- For the teacher: can configure all the permissions.
- For the students: they can try to type the password to get the teacher privilege. Must follow the permissions.

**Permissions**
- students can draw or not
- students send messages or not
- only the teachers can erase messages.

**Comment by francoisschwarzentruber** [comment]
Instead of listening to the lecture, students may spend their time to break the password ;).

**Comment by FrPellegrini** [comment]
Indeed. Up to the teacher not to use a weak password !
https://www.cnil.fr/les-conseils-de-la-cnil-pour-un-bon-mot-de-passe

**Comment by francoisschwarzentruber** [comment]
Here is a glimpse of the new interface for sharing:
![image](https://user-images.githubusercontent.com/43071857/98486277-b5d50f80-221c-11eb-8ffc-960c9a2c0008.png)

Thank you for the discussion and good night.

**Comment by FrPellegrini** [comment]
With the "password" model, it is no use that the sharer and sharee's URLs be different.
In fact, the sharer is the person who creates the tableaunoir / sets the password first.
The teacher has just to be quick enough so that she/he enters her/his password before the pupils can type the URL and set the password ! ;-)

**Comment by FrPellegrini** [comment]
Thanks a lot for being so eager to discuss ! Good night as well.

**Comment by francoisschwarzentruber** [comment]
PS: Yes and... no... he may enter the password before clicking on "make a shared board".

**Comment by francoisschwarzentruber** [comment]
As far as I remember, this issue is solved. I close it but do not hesitate to reopen it if it is not.
