### ISSUE TITLE
Prevent or allow sharees from sending text ?

### ISSUE THREAD

**Issue by FrPellegrini** [tableaunoir/tableaunoir#36]
- When using the shared screen with pupils, there is a risk that they will fill the screen (and those of their mates) with ludicrous comments. Ideally, it would be good that, on the control panel of the sharer, a toggle would exist to enable or disable the chat.

- The same toggle could exist for allowing sharees to draw or not. At the time being, there are two different buttons, but this is really not intuitive, as the sharer cannot know in which state the board is. A toggle would be preferrable, in my opinion.

**Comment by francoisschwarzentruber** [comment]
Thank you for your two points.
- Yes, they can do that. Either we may disable the chat. Or we may add a timeout?
- I agree that these two buttons are not clear. A toggle is clearer.

**Comment by francoisschwarzentruber** [comment]
![image](https://user-images.githubusercontent.com/43071857/98557873-085a0e80-22a5-11eb-9f17-de21855965c8.png)

**Comment by FrPellegrini** [comment]
See what happens when you expose the secret on the web bar :  --D
https://twitter.com/franckconfino/status/1330098064787386371

**Comment by francoisschwarzentruber** [comment]
We may remove the functionality of sending texts, making this issue irrelevant. Does anybody use it?

**Comment by FrPellegrini** [comment]
Personally, I don't. use it.
I use the TableauNoir as a display screen that I broadcast through a video-conferencing system such as BigBlueButton. Maybe sending text could be a useful feature for some other people, but I assume many do like I do, because one needs at least an audio channel to discuss with the pupils/students during the class. Hence the necessity of a third party system, which can convey text per se without hiding the important stuff on the TableauNoir screen.

**Comment by FrPellegrini** [comment]
Applying the "KISS" principle implies to remove this feature, I would say.

**Comment by francoisschwarzentruber** [comment]
Thank you for your advice. I agree... and if anyone really really really wants to ask a question *in* Tableaunoir, just create a magnet with the question inside ;).
