### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#37]
I think Tableaunoir must show the privacy policy. They have to be written clearly. To sum up:
- all data can potentially reach the server and be dispatched to other users connected to the same board.
- the server does not store the boards (is it good or not?)
- options (right-handed or left-handed) are local and stored in localStorage (maybe use cookies instead?)

**Comment by Naereen** [comment]
My thoughts on that:
- perfectly clear
- (I think it's better not to store anything)
- localStorage is better than cookies, because by using cookies you have to display a cookie compliance message (that EU's law), and they are so annoying

**Comment by Naereen** [comment]
@francoisschwarzentruber 6dd2fd5 is great.
Two remarks:

- "Do not forget to the boards you like" -> to what ? To save? To export?
- ".. stored in localStorage." -> (and do not use cookies :no_entry_sign: :cookie: ) ?

**Comment by francoisschwarzentruber** [comment]
Dear Naereen,
thank you for your two remarks. The privacy policy is now fixed.
