### ISSUE TITLE
Pen not active on rightmost quarter of screen

### ISSUE THREAD

**Issue by FrPellegrini** [tableaunoir/tableaunoir#42]
When drawing on a "tableaunoir" instance, either on a PC or an Android smartphone, I ran into the problem that when the cursor gets farther than the rightmost quarter of the board, the pen does not follow the cursor, and when the cursor goes back to the left, then a straight vertical line is drawn between the "exit" and "re-entry" points.

**Comment by francoisschwarzentruber** [comment]
Thank you for your bug report. Do you mean that bug?
![bug_exit_board](https://user-images.githubusercontent.com/43071857/98579401-e8374900-22be-11eb-92a6-163b034e7534.gif)

I removed that bug, but you can draw behind a magnet anymore... I manage to fix it later on.

**Comment by FrPellegrini** [comment]
Yes indeed. But on the right side, not on the top.

**Comment by FrPellegrini** [comment]
(Heyyy ! I got issue #42 ! :-D )

**Comment by francoisschwarzentruber** [comment]
Do you still have the issue?

**Comment by FrPellegrini** [comment]
Nope, it seems solved, thanks !   ^ ^
However, there is just a remaining "glitch". When drawing to the left, right or bottom of the screen, when the pen gets back to the blackboard, drawing resumes. However, when making the pen go up, and then down, drawing does not resume.
