### ISSUE TITLE
Maybe "freeze" the canvas (especially, do not split) when switching left/right ?

### ISSUE THREAD

**Issue by Naereen** [tableaunoir/tableaunoir#44]
Hi.
I love the two features of switching left/right, and splitting the board in two with `d` or the button.

When I try to quickly allocate a few extra "half tabs" to the right, and split them correctly, to prepare for a lecture for instance, if I hit the `d` button *during* the animation to switch left/right, the splitting appears midway, not in the middle of the screen (when animation stops).
See this short GIF for a demo (I frenetically hit `d`, `left`, `right`)
![Peek 12-11-2020 19-07](https://user-images.githubusercontent.com/11994719/98978676-a0146280-251a-11eb-9981-61ccbe48ba6a.gif)

OK it's a weird failure case, as I expect nobody in their right mind will hit buttons that fast, except when trying to break the tool :confused:... but maybe it could be safer to just "freeze" the canvas (making it un-drawable) as long as a left/right animation in happening?

**Comment by francoisschwarzentruber** [comment]
Thank you for that issue. The GIF is very psychedelic! Indeed, it will be solved at some point in the future!

**Comment by Naereen** [comment]
Thanks and good job!
The fix seems great (when looking at the code, that I barely understand), but it does not seem deployed yet so I cannot test and confirm it.
