### ISSUE TITLE
Undo on shared boards

### ISSUE THREAD

**Issue by jmgorius** [tableaunoir/tableaunoir#46]
The *undo* functionality seems not to be working on shared boards. Clicking the button in the toolbar does nothing noticeable.

**Comment by francoisschwarzentruber** [comment]
That issue is not completely solved. Yet, undo redo works for actions that users saw. At least, it will be already useful for people in most cases.

**Comment by Kerl13** [comment]
> That issue is not completely solved. Yet, undo redo works for actions that users saw. At least, it will be already useful for people in most cases.


This is a great improvement for me!

**Comment by francoisschwarzentruber** [comment]
There are two ways for the undo/redo feature:
1) undo will always undo the very last done action, whoever has performed that action
2) undo will undo the last action you have performed. More recent actions done by other users will not be undone.

Now, 1) is implemented. But the code has been reorganized and 2) is implementable. What do you think?

**Comment by jmgorius** [comment]
Option 2) seems more intuitive to me, especially since multiple users may be working on different parts of the same board.

**Comment by francoisschwarzentruber** [comment]
Undo/Redo is muti-user! You undo your own operations!
Code has a bit reorganized:
- the **timeline** contains **actions** (draw a line, erase, add a magnet, move a magnet etc.). It is common to all users (that timeline was the cancel stack, which is not correct)
- Each user has its own **cancel stack**, that contains **operations** (add an action, remove an action, etc.).

**Comment by jmgorius** [comment]
Awesome, thanks a lot! Closing since everything has been fixed.
