### ISSUE TITLE
escape does not render latex

### ISSUE THREAD

**Issue by brabalan** [tableaunoir/tableaunoir#49]
I'm trying the latex renderer in text boxes, but when I hit escape I trigger the menu shortcut instead (the one with help, options, etc.). Is there another key I should use?

**Comment by francoisschwarzentruber** [comment]
Dear brabalan, thank you for your message. What is your system (OS + browser)?

**Comment by brabalan** [comment]
I'm on linux with firefox (82.0.2). If it matters I use tridactyl, and to use tableaunoir I set it in `ignore` mode. Everything else works.

**Comment by francoisschwarzentruber** [comment]
OK, I see. Tableaunoir and tridactyl conflicts because of keyboard shortcuts. I will let you know when I will have solved that issue.

**Comment by brabalan** [comment]
I found the issue. Tableaunoir works great with tridactyl in passthrough mode, but I had umatrix blocking a script. I allowed it and everything works now. Sorry for the noise.
