### ISSUE TITLE
Add an easter egg or hidden feature: generate a new random word to play Pictionnary from tableaunoir

### ISSUE THREAD

**Issue by Naereen** [tableaunoir/tableaunoir#50]
Hi,
I'm in the progress of having a list of words (in French and English) to be used when playing Pictionnary.
I will try to also write a tiny javascript library to easily generate a new random word.
By using it, it should be very easy to add a "hidden" feature (in the menu not the toolbar) in tableaunoir:
- a keyboard shortcut or a menu toggle could add a button on the toolbar
- this button could then be hit to randomly generate a new random word, displayed using a `window.alert()` to only one person (when using shared mode)
I will try to write all this myself, this issue is to track it's development.

**Comment by francoisschwarzentruber** [comment]
What about this issue? Maybe we transform into a discussion?

**Comment by Naereen** [comment]
I'm no longer feeling excited about this idea, so we can close it...
I'll try instead to write a "bookmarklet" that includes my script and so it can be used on any webpage, it will be far simpler than include it in tableaunoir.

**Comment by Naereen** [comment]
I added a "bookmarklet" on the tiny webpage https://naereen.github.io/Free-dictionnaries-for-Pictionnary/index.html, so it can be drap & dropped to a "favorite" toolbar (Firefox, Chrome/Chromium), and then clicked (even offline!) to display a new random word.
Useless, but fun!

**Comment by Naereen** [comment]
It works fine!
![Capture d’écran_2021-03-10_21-25-06](https://user-images.githubusercontent.com/11994719/110693670-facb7b80-81e7-11eb-930e-d795a024ccda.png)

Long live Tableaunoir :heart_eyes: !
