### ISSUE TITLE
Possibility of giving a user name

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#52]
I suggest to add the possibility of adding/changing the user name in the menu. That name could be displayed near the cursor of other participants. I suggest to store that user name in the localStorage so that a user do not need to given a user name at each use.

**Comment by philardine** [comment]
Hi!
Yes it would be useful, I hate not to know who is drawing.
Thanks for this enhancement :-)

**Comment by francoisschwarzentruber** [comment]
Hello Philardine,
thank you for your message. Now, if your colleagues give their pseudos, you will see who is writing.

**Comment by philardine** [comment]
Ah! Thank you very much, I will try it next week with my students :-)
