### ISSUE TITLE
Move the chat in the menu, or remove it?

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#53]
In the current version, tableaunoir in the share mode, provides a chat button for students to ask questions. I must confess that when I used tableaunoir in courses, almost no question were asked with that tool. Also, I think that a student could flood a course if that button is too easy to reach.

There I suggest to move this functionnality in the menu. What do you think?

Another option would be to remove the chat in tableaunoir since tableaunoir is almost always used with another tool for discussing.
What do you think?

**Comment by philardine** [comment]
Hi! Thanx for this good work :-)
I use tableaunoir with other tools for teaching too, and students never use the chat button.
In my opinion the chat could be removed...

**Comment by francoisschwarzentruber** [comment]
Thank you for your message. I actually received other comments also saying that chatting inside tableaunoir is useless or almost useless. I keep this functionality because some people may use it. Anyway, in the menu, it is a nice place for that I think.
