### ISSUE TITLE
Saving as an image has disappeared

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#54]
Hi!
First of all, many thanks for this application. I use it with my students and, personally, I find it more user friendly than other such applications (e.g. whiteboard).
In recent versions, the "saving as image" possibility has disappeared.
I find it useful for students to see the image of the session afterwords.
Do you plan to reactivate this feature in the (hopefully near) future?

**Comment by francoisschwarzentruber** [comment]
Hello,
thank you for having opened an issue. Thank you for your message.
sorry for that. It disappeared because the code switched from Javascript to Typescript. It was difficult for me to use external libraries in Typescript.
Now, it is solved and thus the export in .png works again!

**Comment by philardine** [comment]
Thank you very much :-)
