### ISSUE TITLE
Is it possible to choose black or white chalk color indistinctly in black *and* white boards ?

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#60]
Hi!
The reason is simple: when I write on a blackboard, over a background image with white background, I cannot see where my cursor is.
Workaround: change chalk color to another one ;-)
PS : I think FrPellegrini emitted the same wish somewhere inside enhancement #17

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
thank you for your suggestion. Yes true, it was suggested in #17 and then... I forgot. Sorry for that. I added black *and* white in the palette.
Actually, in a near future, we could make the user chooses its own palette. What do you think?

**Comment by philardine** [comment]
Hey! The ink of my post is not dry, but the issue is yet closed :-) You're faster than Lucky Luke ;-)
If you ask me, I don't think that a personalized color palette is of utmost importance. I eventually regret the little number of colors, not the colors themselves.
Again, thank you for you good work.

**Comment by francoisschwarzentruber** [comment]
Oh I see, you would like to have more colors. Maybe we could image in the option menu, the choice between a simple palette (7 colors) or a 32 colors, and/or... a rainbow with an infinite number of colors.

**Comment by philardine** [comment]
Yes, more than 7 colors my be interesting when you work with a good number of participants (I usually work with about 30 students in the same time).
If it is cheap to implement, perhaps could you offer all three options (7, 32, infinity) for some time, or at least 7 and 32... ?
