### ISSUE TITLE
Deleting text magnet freezes the board

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#61]
Hi!
Today, interacting with my students, the blackboard suddenly became empty for every body, losing everything we wrote.
Here is how to reproduce this behavior:

1. press Enter and type some text
1. draw some line (quit editing the magnet)
1. drag the magnet another place, then delete it (press del key)
1. everything disappear (I mean the other line and the cursor too) and the board is frozen

No matter if you're alone or if you share your board.

PS : I am not very familiar with posting issues, I hope I am not overdoing it by opening so much issues...

**Comment by francoisschwarzentruber** [comment]
Thank you for the bug. I am aware of that. It seems very urgent to be solved!
PS: Your way of doing is perfect. One issue => one issue :)

**Comment by francoisschwarzentruber** [comment]
Thank you for the nice description (1, 2, 3, 4). I was able to reproduce the bug. I will solve that issue soon.

**Comment by francoisschwarzentruber** [comment]
That bug is solved.
PS: Do not laugh! When a text magnet was moved, as its border is tiny, the cursor was on the canvas itself when moving. So the application stored the canvas itself as the current magnet... thus delete the current magnet was deleting... the canvas!

**Comment by philardine** [comment]
Yes I laugh!
Thank you very much this was a very annoying bug.
