### ISSUE TITLE
Strange regression

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#62]
Hi!
On Github.io it is now (26/11/2020 at 21:05) impossible to view the making of a geometric figure (when you drag, and before you drop) after one arrow move, on the second half of the screen :

1. press right arrow (go to screen 2/4)
1. select rectangle tool (for example)
1. go to the right half of the screen and try to drag a rectangle : you don't see the rectangle growing during the drag action, but you can see it after releasing mouse button

**Comment by francoisschwarzentruber** [comment]
Thank you! The underlying SVG element was not big enough.

**Comment by philardine** [comment]
Thank you :-)
