### ISSUE TITLE
Split tool doesn't work anymore

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#63]
Hi!
On Github.io
Try it, the behavior is funny: the line draws, then disappear, then draw... as long as you stay over the tool.
When you leave the tool, there remains no line.

**Comment by francoisschwarzentruber** [comment]
Thank you, the color of the vertical line was wrongly calculated (because I changed something for the exportPng ;) ).
PS: That issue is a typical argument for using unit testing... but such tests are difficult to setup for a graphical user interface.

**Comment by philardine** [comment]
Thank you!
But strangely enough, when you leave the mouse pointer over the split tool, a line regularly draws itself (as I mentioned earlier). Was it your intention?

**Comment by francoisschwarzentruber** [comment]
Yes! That animated line is for showing to the user what this button "divide the screen" means. As this line is always in gray (whatever the type of board, black or whiteboard), there were no wrong color computation in that animation!
Do you think this animation is understandable?

**Comment by philardine** [comment]
Oh! I never noticed this behavior before.
Well I was a little confused, but nothing serious. Isn't it possible to draw the thin gray line *only* when the screen is not yet split?
