### ISSUE TITLE
Toolbar placement

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#64]
Horizontal toolbar on the top/bottom?
Vertical toolbar on the left/right?
Customizable placement?
Remove buttons/add buttons?

**Comment by philardine** [comment]
Hi!
Thank you for giving a place to discuss about this :-)

In my point of view, each user should have the possibility to set the toolbar in a convenient place, and the term *convenient* is totally subjective.
So the choice between left, right, top and down in the option menu could be nice.
But the ultimate option would be if one can drag and drop the toolbar to stick it on whatever border one wants (does it really worth the effort?)

Finally I am not sure to understand well your idea of remove and add buttons. But perhaps wouldn't it be too difficult to implement letting the user build its own toolbar in the option menu (via check boxes for adding or removing the presence of commands in the toolbar).

**Comment by francoisschwarzentruber** [comment]
Hello,
thank you for having pointed out the possibility of changing the placement of the toolbar in another message. :)

The choice between left, right, top and down can be done in the option menu.
The drag and drop is interesting but I feel fear that some users may move the toolbar by mistake and that it is annoying. I think we change the position of the toolbar once in our life, no?

Yes your understand well the idea to customize the toolbar (add/remove buttons). No it is not difficult but I am not sure it is worth.
I think we can postpone the implementation of the customiztion of the toolbar later on.

Do not hesitate to comment, even if I close the issue. ;)

**Comment by philardine** [comment]
I am a little ashamed, because I realize since you implemented this feature that the best way to use tools is to press keys ('e', 't', 'c'...), not to use the toolbar.
So the presence of toolbar becomes not that important (for me at least), not to mention DnD! And, yes, customization can wait.

**Comment by francoisschwarzentruber** [comment]
I have the same use than you: I use the keyboard shortcuts. However, there are users that prefer to use the toolbar, especially the ones on Tablet Android.
The current decision is to:
- keep the current implementation of the toolbar placement
- probably never implement the drag and drop
- postpone the customization

**Comment by morandat** [comment]
Floating, like a magnet, obviously ;)

However customizable is okay. Keyboard shortcuts are fine when you've got a keyboard. Most of the time I'm using a wacom tablet with no keys (and since tableaunoir is not an app for the OS I can't make a profile for it).
No placement is not a one and for all, it is really contextual (depends mainly on where my tableaunoir is casted) ; but the context is for a full session, thus a menu is perfectly fine.

**Comment by philardine** [comment]
I find this idea very nice :-)
