### ISSUE TITLE
A new shape: arcs (click for the center + you draw)

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#68]
To draw arcs like you with a compass:
- pick the center
- and draw (the first point determines the radius)
What do you think?

**Comment by philardine** [comment]
Can be useful, especially for teaching mathematics, or for drawing regular mouths within emoticons ;-)

**Comment by francoisschwarzentruber** [comment]
As far as I remember of my geometry classes, I think we often need to reuse the radius no? Determining the radius each time annoying no?

**Comment by philardine** [comment]
I am afraid I don't understand.
For me, you first clic to select the center, then you lift the pencil and put it down a little further, thus starting to draw an arc... and that's all, isn't it?
I don't understand how you can "reuse the radius"...?

**Comment by francoisschwarzentruber** [comment]
Sorry for not having been clear. There are applications for which one needs to draw several arcs of the _same_ radius.

Example of drawing the line segment bisector (médiatrice)
a) suppose a horizontal segment AB is drawn
b) draw two small arcs centered at A of some radius r, one at the top, one at the bottom
c) draw two small arcs centered at B of the _same_ radius r, one at the top, one at the bottom
d) The intersection of the arcs gives two points C and D and (CD) is the line segment bisector of [AB]

Let us consider the solution 1. click for the center, 2. click choosing the radius and starting to draw 3. mouse up when the arc is finished. That solution does not allow easily to reuse the _same_ radius r at step c), because you will be stuck at step 2.

The only solution I can imagine is to mimic the use a compass. The tool shows three gadgets:
i) the center that can be dragged. 
ii) a virtual point that enables to change the radius (if you want another radius)
iii) the chalk, when moved it draws an arc.
To reuse the same radius, simply move the center, and do not touch to the virtual point to keep the same radius.

What do you think?

**Comment by philardine** [comment]
Thank you for your detailed explanation.
I didn't figure out the concept of *reusable* radius, I understand it now.

Then let me reformulate your proposal (to see if I understand it well):
1. select arc tool in the 't' menu
1. then 2 magnets (kind of crosses?) appear on the board: one representing the center (under the current mouse pointer position), and another one representing a point at some distance from the first (the last distance defined, or default).
1. drag these 2 magnets at will
1. draw with chalk creates arcs (what about interference between the drawing and the radius point magnet? see below...)
1. repeat the two preceding steps at will
1. leave the tool, and the magnets disappear (btw, they cannot be deleted by the user while the tool is active)

And when you leave the arc tool, then activate it again, the magnets reappear relatively to the current mouse pointer.

What about a variant where there is only one extensible magnet showing the center and the radius defining point (for example an invisible line with only visible extremities)?
The center extremity reacts to drag by moving the magnet, the radius point reacts to drag by extending the magnet, and the magnet rotates if the chalk needs to draw under the radius point (as if the drawing pushed the magnet, rotating around its center)?

What do you think?

**Comment by francoisschwarzentruber** [comment]
Thank you!! I thought exactly the same thing!!! ...  except for the whole magnet to rotate if the chalk needs to draw under the radius point. :)

**Comment by francoisschwarzentruber** [comment]
Implemented!! But does not work yet in share mode ;)
The rotation is not implemented yet (instead the radius handle is hidden when drawing)
![smiley](https://user-images.githubusercontent.com/43071857/100635356-b7cc5300-3330-11eb-8808-e3a8370f5852.gif)

**Comment by francoisschwarzentruber** [comment]
Two things to be solved now:
- share
- the drawing itself that remain always on the circle

**Comment by philardine** [comment]
Waw! Very nice :-)

**Comment by Naereen** [comment]
Is this issue finished? I guess it can be closed.

**Comment by francoisschwarzentruber** [comment]
It works on single boards, but is buggy on shared boards. I can handle that at some point!
