### ISSUE TITLE
The copy button for share link doesn't seem to work

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#69]
Hi!
It's a minor flaw, but the copy button for share link in the menu/Share panel doesn't seem to copy to clipboard... :-P

**Comment by francoisschwarzentruber** [comment]
Yes :( Some browsers do not allow to copy-paste :(

**Comment by morandat** [comment]
Which Browser are you using. For Safari there's nothing to hope never (it's disabled on purpose), for other browser some technics seems more reliable than other (and there is a way to ask what's supported). One day this should be fixed/investigate.

**Comment by philardine** [comment]
Well, I just realized that it's OK with Firefox, but I can't copy with Chromium...

**Comment by Naereen** [comment]
I don't find references showing that this copy from javascript cannot be done on Chrome or Chromium.
[This page from 2015 on Chrome update website](https://developers.google.com/web/updates/2015/04/cut-and-copy-commands?hl=en) seems to say it's been supported for a long time.

**Comment by philardine** [comment]
Hello Naereen,

Thank you for your interest on this subject :-)

At the moment, neither with Firefox 85.0 nor with Chromium 88.0.4324.50 (both under Linux Mint 20.04) I **cannot** copy to the clipboard using the « Copy » button in the Share panel of the Menu...

**Comment by tekhnee** [comment]
Speaking of this, is the URL meant to be user-adjustable or only machine-generated?

My impression is the latter. In that case, it might make sense to make the text field read-only.

(If my impression is wrong, I'll stand corrected :)

**Comment by philardine** [comment]
Hello!

@Tekhnee I agree with you.
@All here is a screenshot of what happens in the Chromium console (read the last message): 
![trace_copyShareUrl](https://user-images.githubusercontent.com/68193108/108357611-f2d27a00-71ed-11eb-8b7d-1d7f4008a660.png)

Thank you all for your help.

**Comment by francoisschwarzentruber** [comment]
Hello,

thank you for your messages.

@tekhnee 
Thank you for pointed that issue. Yes, the text-field is now readonly. However, if you type a self-adjusted id for your board in the address bar, it normally works.

@philardine 
- Now the translation errors are quieter (there are still there, it means that some language file does not mention properly the id's given in the html file). These errors are harmless: just some part of the interface will not be translated.
- the error about users/undefined haas been corrected (see issue #139) But the new version is not deployed on irisa.fr yet!
- Concerning the "copy to clipboard error", I do not have it on my computer (Linux, Chrome 88.0.4324.182). According to https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API, it should work on Chrome >= 66. Probably, an option somewhere that prevents clipboard operations?

Have a nice day! Still another clipboard-free day...

**Comment by philardine** [comment]
Hello everybody!

I realized that there exists 2 access modes for Tableaunoir (on irisa.fr): one which is secured (HTTPS), and the other not (HTTP).
I used to use the unsecured access. I am not sure I understood the web API correctly but (if I don't say nonsense) it seems to me that navigator.clipboard.writeText should be usable only over secured access. Could it be the origin of my problem?

By the way, when I attempt to connect to the secured version, I get the following message « Problem in loading Tableaunoir... please try to clear the cache of your browser. »... which remains even after clearing the cache.

**Comment by francoisschwarzentruber** [comment]
Hello!

Thank you thank you! It is maybe related! I also have the error with navigator.clipboard.writeText on Firefox and Chrome from http://tableaunoir.irisa.fr !

Yes, HTTPS does not work because I do not understand how we manage to setup a secure connexion on the server side. I spend an afternoon trying to understand how certificates are used without success (in french, "je me suis arraché les cheveux"). I sould spend more time on it. I know that there exists some instances of Tableaunoir which works with HTTPS but the irisa.fr one!

**Comment by tekhnee** [comment]
@francoisschwarzentruber i struggled a little but managed to set up an https/wss instance of tableaunoir behind a reverse proxy in Apache. Happy to try to help if that’s your server platform. Unfortunately ngix is out of my depth as I’ve never used it.

**Comment by Kerl13** [comment]
Hi François, in case you are using nginx, I might be of some help too. Cheers

**Comment by francoisschwarzentruber** [comment]
Dear Kerl13,
thank you so for your help. No, I am not using nginx. I have never used that tool... :( I must learn.

**Comment by morandat** [comment]
Sorry I'm out of the discussion since a while.
Clipboard is a pain ; that's a fact (however that's for good reason). Definitely this API won't work on safari, and for other may only work on secure channels.
Having a secure connection is mainly a question of having a certificate (for both nginix&apache) ; however self-signed certificates doesn't work (except localy for testing purpose). If your server is easily reachable (i.e., not in a uni), the let's encrypt project is for you ! Docs & tools are well documented.

@francoisschwarzentruber I'm currently underwater (to write anything), but I'm always in for a call sometime.

**Comment by francoisschwarzentruber** [comment]
Thank you @morandat for your solution when the website is not in a uni.
Also really thank you @Kerl13 for the discussion and for having helped me to setup https on https://tableaunoir.irisa.fr/ that now works.

Does anyone still have trouble with the clipboard when the website starts with https?
If no, we could close this issue!

**Comment by philardine** [comment]
Dear François,
I am glad to say: Hurray! The copy button for share link works fine for me on https :-)
Thank you all for the good work, always in progress!

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
Excellent! :) And thank you for your support!
I then close this issue.

**Comment by Naereen** [comment]
It's great if this copy button works.

But IMHO, having to manually copy-paste is not such a burden: we do it so often for everything that one more, one less time...
