### ISSUE TITLE
Sometimes stuck on the message "Welcome in tableaunoir..."

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#73]
Maybe a problem in the message passing system (the acknowledgement may not be received, processed?)

**Comment by philardine** [comment]
Hello François,
I have just experienced this problem (sharing with me and me on tableaunoir.irisa), but cannot reproduce it...

**Comment by francoisschwarzentruber** [comment]
Hello Philardine,
Neither do I. Hope this bug will show up again, otherwise it will be difficult to solve it. ;)

**Comment by philardine** [comment]
1. start a fresh board at http://tableaunoir.irisa.fr
1. go to menu/share and share it...
1. return to the board then press F5
1. you always get "Welcome to tableaunoir. The shared board you are trying to reach will appear soon. Please wait..."

**Comment by francoisschwarzentruber** [comment]
Thank you again for the detailed path to reach the bug. The problem arrived when you are alone. 

PS: You are waiting waiting waiting for some news of an existing board, but you already have all the information! So the message was there, and never removed because the server did not send you information.
In the correction version, by default, you do not wait, but you quickly receive a message "wait wait..." if you are not alone, making the message "Welcome in tableaunoir..." appearing. Once you get the message "you are ready!", the message disappears and you can modify the board!

**Comment by philardine** [comment]
OK! Thank you :-)

PS : I've had some cold sweat this morning when I was preparing a tableaunoir 5 mn before the start of my course, and I was waiting for ever, thinking I could not use it because of some weird bug :-D

**Comment by philardine** [comment]
Hello François,

The problem does not seem to be completely resolved.
I've had a flashing message this afternoon (perhaps when some of my 30 students where connecting or pressing F5? I don't know), but I could still draw while the message was flashing.
Sorry, I cannot tell more about this...
