### ISSUE TITLE
Cannot draw on the last fourth of the board

### ISSUE THREAD

**Issue by philardine** [tableaunoir/tableaunoir#78]
Hi!

Do the following:
1. press Shift + right arrow
1. press right arrow two times
1. press Shift + right arrow
1. press right arrow two times

Now try to draw on the last fourth (right) of the board: it's impossible!
Is it an easter egg ;-)

PS: I think that a previous issue was already talking about this problem but sorry, I can't get my hands on it...

**Comment by francoisschwarzentruber** [comment]
Yes, there are no bugs, only easter eggs ;)
That bu..easter egg will be solved soon.

**Comment by francoisschwarzentruber** [comment]
Dear Philardine,
I hope you are fine. This issue is now solved I think. Thank you again for pointing that issue.

**Comment by philardine** [comment]
Thank you François :-)
