### ISSUE TITLE
"Interpreted" text magnets

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#81]
Hello, I want to discuss here a notion proposed by Bernard Parisse in his fork of tableaunoir: "interpreted" text magnets. See 
https://www-fourier.univ-grenoble-alpes.fr/~parisse/tableaunoirxcas/#mat309/myblackboard.tableaunoir

Have the notion of "interpreted" text magnets may elegantly solve issue #28.

The idea is as follows: the creation of text magnets is as usual. Once the text magnet created, you can switch between different type of "interpretation" in the text toolbar (the text toolbar will replace the normal toolbar when a text magnet is selected):
- normal (just type text, as usual, I guess you could not anymore write LaTEX equations)
- LaTEX equations (the text magnet contains the LaTEX code and it displays the formula)
- a simple language for equations ("1/2" will display the equivalent of "\frac 1 2", but you teach it usually anoying to think in LaTEX commands)
- interpretation of Javascript/Python/XCas expressions, to do maths as in tableaunoirxcas

What do you think?

**Comment by Naereen** [comment]
> - interpretation of Javascript/Python/XCas expressions, to do maths as in tableaunoirxcas
I think this is way too much complicated!

**Comment by Naereen** [comment]
> - a simple language for equations ("1/2" will display the equivalent of "\frac 1 2", but you teach it usually anoying to think in LaTEX commands)

It's a good idea, but I think it's unnecessary: if you don't have time to write fractions, then display 1/2 as 1/2 and not ¹/2 is no big deal, IMHO.

**Comment by francoisschwarzentruber** [comment]
I think we will not implement this feature soon.
