### ISSUE TITLE
Unclear message « The server will not save your board. » 

### ISSUE THREAD

**Issue by JocelynDelalande** [tableaunoir/tableaunoir#83]
![image](https://user-images.githubusercontent.com/429633/102830112-e6e25b80-43e8-11eb-836c-9236dfc07d28.png)

What does it mean exactly ?

**Comment by francoisschwarzentruber** [comment]
Dear Jocelyn,

thank you for your message. I agree that the message "Warning: The server will not save your board" sounds unclear and aggressive (like if you have done something wrong, especially something wrong in your pseudo ;) ).
Now, it has been replaced by the following message placed at the top of the menu page:

> For privacy reasons, this board is not stored on the server. Save the board on your device at the end of the session if needed.

Merry christmas to you and stay safe!
