### ISSUE TITLE
A space insertion tool

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#85]
You forgot to type a word?
You want to insert a panel?
You want to add an illustration?

It would be very nice to have an intuitive tool to insert space. Not clear yet how to do that.

**Comment by Naereen** [comment]
What do you mean "insert space" ?
Insert a vertical panel *between two other panels*?

**Comment by francoisschwarzentruber** [comment]
For instance, yes. Actually, when I teach, I never really experience this need. May this issue is not very important. Or maybe we should convert this issue in a discussion?
