### ISSUE TITLE
Draw graphs (vertices + edges)

### ISSUE THREAD

**Issue by francoisschwarzentruber** [tableaunoir/tableaunoir#86]
It would be very nice that tableaunoir recognizes/helps you to draw graphs. Then when a vertex is moved, the rest of the graph follows etc.

**Comment by francoisschwarzentruber** [comment]
Here is a preview of this functionality.
![tableaunoir_graph](https://user-images.githubusercontent.com/43071857/103108293-e0e9b600-4646-11eb-8f5c-73d907dab75f.gif)

What do you think? Will it be useful for you?

Next:
- self loops?
- maybe edge labels?
- remove edges with the eraser?

And merry christmas!

**Comment by tekhnee** [comment]
@francoisschwarzentruber this looks excellent. Working with your own bullet list:

- ~self loops?~ allow arbitrary number of arcs between 
- maybe edge labels?
- remove edges with the eraser?
- ~bend edges for avoiding overlapping with existing edges and nodes?~ Maybe a more general solution to the same problem (maybe a bezier or parabola-like curve with a control point in the middle)? What I have in mind is a instant way to draw things like a legato slur ;)
     - As an alternative or complement to this, a means of stretching/shrinking *in its handwritten form* would also be extremely eloquent and useful.

Thank you so much for this work — and merry christmas!

**Comment by slel** [comment]
Wonderful! Desirable features for a graph editor:

- support directed as well as undirected graphs
- support graphs with loops and/or with multiple edges
- support labelling vertices and edges
- support setting vertex colour, font, shape
- support setting edge colour, thickness, arrow style
- provide adjacency matrix, graph6 code, digraph6 code
- export as pdf, png, pstricks, svg, tikz
- check planarity, compute shortest paths, ...
- provide various layout functions: circular, planar, spring, ...

For inspiration about common or desirable graph editor features:

- Graph-editor topic on GitHub
  https://github.com/topics/graph-editor
- Question: Tool for drawing graph and getting graph6 code
  https://stackoverflow.com/q/63803031
- Quick and dirty graph editor
  https://github.com/nvcleemp/qdge
- GWT graph editor
  https://github.com/nvcleemp/grapheditor
- Benzene graph editor
  https://github.com/nvcleemp/benzene-editor
- SageNB graph editor (archived)
  https://github.com/sagemath/sagenb/tree/b360a0172e15501fb0163d02dce713a561fee2af/sagenb/data/graph_editor
- Sage Trac ticket 30540: Provide graph editor that works with Jupyter
  https://trac.sagemath.org/ticket/30540
- pgf/tikz documentation, §3: Tutorial: A Petri-Net for Hagen
  https://pgf-tikz.github.io/pgf/pgfmanual.pdf

**Comment by francoisschwarzentruber** [comment]
Dear tekhnee, dear slel,

thank you for your messages! Thank you tekhnee for your nice idea that is now just implemented: 
> As an alternative or complement to this, a means of stretching/shrinking an arc in its handwritten form would also be extremely eloquent and useful.

Thank you slel for your nice list of features.
    support directed as well as undirected graphs: partially done (drawing the arrow is perfect yet)
    support graphs with loops and/or with multiple edges: done
    support labelling vertices and edges: difficult
    support setting vertex colour, font, shape: partially done (magnets can have any shape and can be of any color)
    support setting edge colour, thickness, arrow style: partially done
    provide adjacency matrix, graph6 code, digraph6 code: would be nice!
    export as pdf, png, pstricks, svg, tikz: especially tikz ;)
    check planarity, compute shortest paths, ... why not :)
    provide various layout functions: circular, planar, spring, ...: why not :) For the moment the layout is done by hand.

As Tableaunoir is used for teaching and is not a drawing program, I suggest Tableaunoir to be as simple to use as a blackboard: just draw/erase and move magnets. The philosophy I try to follow is: minimize the number of buttons. You want to draw a thicker line? Just insist and draw it several times? You need to draw a dash line? Just use the eraser to remove some part of the line. You need to draw an arrow? Just draw an arrow :).

Here is a new preview of this functionnality.

![graph](https://user-images.githubusercontent.com/43071857/103134888-a3bc0d00-46b4-11eb-8766-29b006bb3d5f.gif)

And... merry christmas!

**Comment by Naereen** [comment]
What is there to do on this issue?
The new feature seems to work very well, maybe this issue can be closed?

**Comment by francoisschwarzentruber** [comment]
It is not perfect. For instance, sometimes, tableaunoir does not understand that a line should be an edge. Or it wrongly detects an edge. But this feature is difficult to be perfectly implemented. What do you think?

**Comment by francoisschwarzentruber** [comment]
Probably, some specific issues should be added. Also, the implementation of this feature cannot be "perfect". So I close the issue.
